"""empty message

Revision ID: 9e8e17d2ec73
Revises: d63d19773006
Create Date: 2021-03-28 17:40:29.889610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8e17d2ec73'
down_revision = 'd63d19773006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('algorithms_configuration_id_fkey', 'algorithms', type_='foreignkey')
    op.drop_column('algorithms', 'configuration_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('algorithms', sa.Column('configuration_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('algorithms_configuration_id_fkey', 'algorithms', 'configurations', ['configuration_id'], ['id'])
    # ### end Alembic commands ###
