"""empty message

Revision ID: d63d19773006
Revises: 548e58fb70e8
Create Date: 2021-03-28 16:26:59.131189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd63d19773006'
down_revision = '548e58fb70e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('algorithms', sa.Column('configuration_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'algorithms', 'configurations', ['configuration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'algorithms', type_='foreignkey')
    op.drop_column('algorithms', 'configuration_id')
    # ### end Alembic commands ###
